import { FormikProps } from "formik"
import { DatePickerProps } from "react-datepicker";
import { DayPickerProps } from "react-day-picker";

export type FormikDatePickerProps<T> = DatePickerProps & {
  /** The formik value generated by useFormik */
  formik: FormikProps<T>;

  /** Name of the field you want to use formik with */
  field: string;
  
  /** Date format, defaults as dd/mm/yyyy */
  formatter?: Intl.DateTimeFormat;

  /** Name of the field you want to use formik with */
  defaultValue: string;
}

export type AdapterType = (event?: React.MouseEvent<HTMLElement> | React.KeyboardEvent<HTMLElement>) => void

export type AdapterProps = React.MouseEvent<HTMLElement, MouseEvent> | React.KeyboardEvent<HTMLElement> | undefined;