import { FormikProps } from "formik"
import { DatePickerProps } from "react-datepicker";

type FormikDatePickerProps<T> = DatePickerProps & {
  /** The formik value generated by useFormik */
  formik: FormikProps<T>;

  /** Name of the field you want to use formik with */
  field: string;
  
  /** Date format, defaults as dd/mm/yyyy */
  formatter?: Intl.DateTimeFormat;

  /** Name of the field you want to use formik with */
  defaultValue?: string;
}

type AdapterType = (event?: React.MouseEvent<HTMLElement> | React.KeyboardEvent<HTMLElement>) => void

type AdapterProps = React.MouseEvent<HTMLElement, MouseEvent> | React.KeyboardEvent<HTMLElement> | undefined;

export type { FormikDatePickerProps, AdapterType, AdapterProps };